### ISSUE TITLE
Fails to build on 0.8.0

### ISSUE THREAD

**Issue by irfaan** [chirag04/react-native-tooltip#1]
Receiving this error when trying to build: 

```
/[...]/node_modules/react-native-tooltip/ToolTipMenu/RCTToolTipText.m:27:23: No visible @interface for 'RCTEventDispatcher' declares the selector 'sendTextEventWithType:reactTag:text:eventCount:'
```

Any ideas?

**Comment by chirag04** [comment]
v0.8.0 is not supported anymore in the latest version of tooltip. If you still want to use it download v0.1.5 of react-native-tooltip

**Comment by irfaan** [comment]
Thanks! Managed to find time to downgrade. Hitting this error using 0.1.5 on 0.8.0:

`[error][tid:main][ToolTipMenu.m:25] Cannot find view with tag #(null)`

Any ideas?

**Comment by chirag04** [comment]
Hi ifran,

Like i said, you should upgrade to the latest version. RN is 0.12 now also.

As for the specific error, it seem the view is not passed on correctly to native side. Are you using `React.findNodeHandle(this.refs.input)`?

Make sure this.refs.input is not null.

**Comment by irfaan** [comment]
Thanks @chirag04. I bit the bullet and managed to upgrade to 0.12. Now to see if I can get tooltip working smoothly! Thanks for getting back to me.

**Comment by chirag04** [comment]
:+1: awesome. 

It would be interesting to know how you are using tooltip in your project. just out of curiosity. ;)

**Comment by passol1988** [comment]
this error also occurs on **0.14.0(react-native)** when I want to build 
no visible @interface for 'RCTEventDispatcher' declares the selector 'sendTextEventWithType:reactTag:text:key:eventCount:' ?

**Comment by passol1988** [comment]
finally, I found **_eventDispatcher** have changed , so I need modify this to adapt 0.14.0
*\* [_eventDispatcher sendTextEventWithType:RCTTextEventTypeChange  reactTag:self.reactTag text:text eventCount:_nativeEventCount];**

**Comment by chirag04** [comment]
@passol1988 for reactnative 0.14 use tooltip version `2.3.0`.

`3.x` for this module is supporting react native 15+
