### ISSUE TITLE
React.PropTypes is removed in RN 0.49

### ISSUE THREAD

**Issue by fungilation** [chirag04/react-native-tooltip#31]
What used to be a warning: `Warning: PropTypes has been moved to a separate package` is now a removal, and redbox error in RN 0.49.3:
<img width="487" alt="screenshot 2017-10-10 13 32 06" src="https://user-images.githubusercontent.com/3803466/31409107-973166b6-adbf-11e7-9f49-6f87224c1375.png">

Need a fix like https://github.com/clauderic/react-native-highlight-words/pull/4/files

**Comment by enahum** [comment]
This is fixed now, I’ll close the issue, feel free to re-open in any case
